# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_man(object):
    def setupUi(self, man):
        man.setObjectName("man")
        man.resize(1164, 768)
        self.tableWidget = QtWidgets.QTableWidget(man)
        self.tableWidget.setGeometry(QtCore.QRect(20, 70, 441, 281))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setIconSize(QtCore.QSize(0, 0))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 4, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(80)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setDefaultSectionSize(31)
        self.checkBox = QtWidgets.QCheckBox(man)
        self.checkBox.setGeometry(QtCore.QRect(330, 40, 71, 16))
        self.checkBox.setObjectName("checkBox")
        self.pushButton = QtWidgets.QPushButton(man)
        self.pushButton.setGeometry(QtCore.QRect(110, 40, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.find_str = QtWidgets.QLineEdit(man)
        self.find_str.setGeometry(QtCore.QRect(20, 370, 311, 31))
        self.find_str.setText("")
        self.find_str.setObjectName("find_str")
        self.pushButton_2 = QtWidgets.QPushButton(man)
        self.pushButton_2.setGeometry(QtCore.QRect(340, 370, 91, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.etl_job_list = QtWidgets.QTableWidget(man)
        self.etl_job_list.setGeometry(QtCore.QRect(20, 410, 441, 241))
        self.etl_job_list.setMinimumSize(QtCore.QSize(0, 241))
        self.etl_job_list.setStyleSheet("alternate-background-color: rgb(187, 255, 183);")
        self.etl_job_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.etl_job_list.setAlternatingRowColors(True)
        self.etl_job_list.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.etl_job_list.setObjectName("etl_job_list")
        self.etl_job_list.setColumnCount(4)
        self.etl_job_list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.etl_job_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.etl_job_list.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.etl_job_list.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.etl_job_list.setHorizontalHeaderItem(3, item)
        self.etl_job_list.horizontalHeader().setCascadingSectionResizes(False)
        self.etl_job_list.horizontalHeader().setSortIndicatorShown(False)
        self.etl_job_list.horizontalHeader().setStretchLastSection(False)
        self.etl_job_list.verticalHeader().setVisible(True)
        self.etl_job_list.verticalHeader().setCascadingSectionResizes(False)
        self.etl_job_list.verticalHeader().setSortIndicatorShown(False)
        self.etl_job_list.verticalHeader().setStretchLastSection(False)
        self.dateEdit_2 = QtWidgets.QDateEdit(man)
        self.dateEdit_2.setGeometry(QtCore.QRect(-10, 1030, 110, 22))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.spinBox = QtWidgets.QSpinBox(man)
        self.spinBox.setGeometry(QtCore.QRect(280, 40, 42, 22))
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(120)
        self.spinBox.setSingleStep(5)
        self.spinBox.setProperty("value", 1)
        self.spinBox.setDisplayIntegerBase(10)
        self.spinBox.setObjectName("spinBox")
        self.dept_tab = QtWidgets.QTableWidget(man)
        self.dept_tab.setGeometry(QtCore.QRect(590, 280, 501, 241))
        self.dept_tab.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.dept_tab.setAlternatingRowColors(True)
        self.dept_tab.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.dept_tab.setObjectName("dept_tab")
        self.dept_tab.setColumnCount(5)
        self.dept_tab.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.dept_tab.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.dept_tab.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.dept_tab.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.dept_tab.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.dept_tab.setHorizontalHeaderItem(4, item)
        self.dept_tab.verticalHeader().setVisible(True)
        self.layoutWidget = QtWidgets.QWidget(man)
        self.layoutWidget.setGeometry(QtCore.QRect(660, 210, 155, 18))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dept_type_all = QtWidgets.QRadioButton(self.layoutWidget)
        self.dept_type_all.setChecked(True)
        self.dept_type_all.setObjectName("dept_type_all")
        self.dep_updw_Group = QtWidgets.QButtonGroup(man)
        self.dep_updw_Group.setObjectName("dep_updw_Group")
        self.dep_updw_Group.addButton(self.dept_type_all)
        self.horizontalLayout.addWidget(self.dept_type_all)
        self.dept_up = QtWidgets.QRadioButton(self.layoutWidget)
        self.dept_up.setObjectName("dept_up")
        self.dep_updw_Group.addButton(self.dept_up)
        self.horizontalLayout.addWidget(self.dept_up)
        self.dept_down = QtWidgets.QRadioButton(self.layoutWidget)
        self.dept_down.setObjectName("dept_down")
        self.dep_updw_Group.addButton(self.dept_down)
        self.horizontalLayout.addWidget(self.dept_down)
        self.layoutWidget1 = QtWidgets.QWidget(man)
        self.layoutWidget1.setGeometry(QtCore.QRect(850, 210, 227, 18))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.denpt_all = QtWidgets.QRadioButton(self.layoutWidget1)
        self.denpt_all.setObjectName("denpt_all")
        self.dep_lvl_Group = QtWidgets.QButtonGroup(man)
        self.dep_lvl_Group.setObjectName("dep_lvl_Group")
        self.dep_lvl_Group.addButton(self.denpt_all)
        self.horizontalLayout_2.addWidget(self.denpt_all)
        self.two_dept = QtWidgets.QRadioButton(self.layoutWidget1)
        self.two_dept.setObjectName("two_dept")
        self.dep_lvl_Group.addButton(self.two_dept)
        self.horizontalLayout_2.addWidget(self.two_dept)
        self.one_dept = QtWidgets.QRadioButton(self.layoutWidget1)
        self.one_dept.setChecked(True)
        self.one_dept.setObjectName("one_dept")
        self.dep_lvl_Group.addButton(self.one_dept)
        self.horizontalLayout_2.addWidget(self.one_dept)
        self.layoutWidget2 = QtWidgets.QWidget(man)
        self.layoutWidget2.setGeometry(QtCore.QRect(140, 690, 225, 25))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.layoutWidget2)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.data_dt = QtWidgets.QDateEdit(self.layoutWidget2)
        self.data_dt.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 10, 5), QtCore.QTime(0, 0, 0)))
        self.data_dt.setCurrentSectionIndex(1)
        self.data_dt.setDate(QtCore.QDate(2019, 10, 5))
        self.data_dt.setObjectName("data_dt")
        self.horizontalLayout_3.addWidget(self.data_dt)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)

        self.retranslateUi(man)
        self.pushButton.clicked.connect(man.click_refase)
        self.checkBox.stateChanged['int'].connect(man.auto_refs)
        self.spinBox.editingFinished.connect(man.auto_refs)
        self.dept_type_all.toggled['bool'].connect(man.dep_tog)
        self.dept_up.toggled['bool'].connect(man.dep_tog)
        self.dept_down.toggled['bool'].connect(man.dep_tog)
        self.denpt_all.toggled['bool'].connect(man.dep_tog)
        self.two_dept.toggled['bool'].connect(man.dep_tog)
        self.one_dept.toggled['bool'].connect(man.dep_tog)
        self.pushButton_2.clicked.connect(man.find_job)
        self.find_str.returnPressed.connect(man.find_job)
        self.pushButton_3.clicked.connect(man.again_job)
        QtCore.QMetaObject.connectSlotsByName(man)

    def retranslateUi(self, man):
        _translate = QtCore.QCoreApplication.translate
        man.setWindowTitle(_translate("man", "大零售调度平台"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("man", "加载"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("man", "转换"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("man", "导出"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("man", "传送"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("man", "同步"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("man", "回流"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("man", "其他"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("man", "全部"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("man", "完成"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("man", "准备"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("man", "运行"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("man", "失败"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("man", "总作业"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("man", "1111"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("man", "2222"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("man", "111"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("man", "111"))
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("man", "1111"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.checkBox.setText(_translate("man", "自动刷新"))
        self.pushButton.setText(_translate("man", "刷新"))
        self.find_str.setPlaceholderText(_translate("man", "请输入作业码或者作业名称"))
        self.pushButton_2.setText(_translate("man", "查找作业"))
        item = self.etl_job_list.horizontalHeaderItem(0)
        item.setText(_translate("man", "作业"))
        item = self.etl_job_list.horizontalHeaderItem(1)
        item.setText(_translate("man", "作业名称"))
        item = self.etl_job_list.horizontalHeaderItem(2)
        item.setText(_translate("man", "作业状态"))
        item = self.etl_job_list.horizontalHeaderItem(3)
        item.setText(_translate("man", "操作"))
        self.spinBox.setSuffix(_translate("man", "秒"))
        item = self.dept_tab.horizontalHeaderItem(0)
        item.setText(_translate("man", "依赖类型"))
        item = self.dept_tab.horizontalHeaderItem(1)
        item.setText(_translate("man", "作业"))
        item = self.dept_tab.horizontalHeaderItem(2)
        item.setText(_translate("man", "作业名称"))
        item = self.dept_tab.horizontalHeaderItem(3)
        item.setText(_translate("man", "目标表"))
        item = self.dept_tab.horizontalHeaderItem(4)
        item.setText(_translate("man", "作业状态"))
        self.dept_type_all.setText(_translate("man", "全部"))
        self.dept_up.setText(_translate("man", "上游"))
        self.dept_down.setText(_translate("man", "下游"))
        self.denpt_all.setText(_translate("man", "所有依赖"))
        self.two_dept.setText(_translate("man", "二层依赖"))
        self.one_dept.setText(_translate("man", "一层依赖"))
        self.label.setText(_translate("man", "会计日期："))
        self.data_dt.setDisplayFormat(_translate("man", "yyyyMMdd"))
        self.pushButton_3.setText(_translate("man", "强制重调"))
